export const PLAYERS_LIST_REQUEST = 'PLAYERS_LIST_REQUEST';
export const PLAYERS_LIST_RECEIVED = 'PLAYERS_LIST_RECEIVED';
export const PLAYERS_LIST_ERROR = 'PLAYERS_LIST_ERROR';
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD';
export const PLAYERS_LIST_SET_PAGE = 'PLAYERS_LIST_SET_PAGE';

export const CLUB_REQUEST = 'CLUB_REQUEST';
export const CLUB_RECEIVED = 'CLUB_RECEIVED';
export const CLUB_ERROR = 'CLUB_ERROR';
export const CLUB_UNLOAD = 'CLUB_UNLOAD';
export const BLOG_POST_FORM_UNLOAD = 'BLOG_POST_FORM_UNLOAD';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_RECEIVED = 'COMMENT_LIST_RECEIVED';
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';
export const COMMENT_LIST_UNLOAD = 'COMMENT_LIST_UNLOAD';

export const COMMENT_ADDED = 'COMMENT_ADDED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';
export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const IMAGE_DELETED = 'IMAGE_DELETED';
export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';

